/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 25 21:35:06 GMT 2026
 */

package org.apache.bookkeeper.bookie;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.channels.ClosedChannelException;
import java.nio.charset.Charset;

import org.apache.bookkeeper.conf.ServerConfiguration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = false, resetStaticState = true, separateClassLoader = true)
public class JournalChannel_ESTest extends JournalChannel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockFile mockFile0 = new MockFile("w7oPVgP1Tk9LC[pdA9", "0O\"lt2>hy");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 1048576L, 1048576L, 512, serverConfiguration0, defaultFileChannelProvider0);
      Charset charset0 = Charset.defaultCharset();
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      ByteBuffer byteBuffer0 = charset0.encode(charBuffer0);
      int int0 = journalChannel0.read(byteBuffer0);
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MockFile mockFile0 = new MockFile("", "");
      // Undeclared exception!
      try { 
        JournalChannel.renameJournalFile(mockFile0, mockFile0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MockFile mockFile0 = new MockFile("", "");
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 86400000L);
      // Undeclared exception!
      try { 
        journalChannel0.read((ByteBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, 1000000000L);
      JournalChannel journalChannel1 = new JournalChannel((File) null, 2820L);
      journalChannel1.close();
      try { 
        journalChannel1.preAllocIfNeeded(1000000000L);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(ClosedChannelException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, (-795L));
      JournalChannel journalChannel1 = new JournalChannel((File) null, (-795L));
      // Undeclared exception!
      try { 
        journalChannel1.preAllocIfNeeded(6);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MockFile mockFile0 = new MockFile("us@+jxT*", "us@+jxT*");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 4, 4, 4, 4, true, 4, serverConfiguration0, defaultFileChannelProvider0);
      journalChannel0.nextPrealloc = (-181L);
      // Undeclared exception!
      try { 
        journalChannel0.preAllocIfNeeded(4);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, (-811L));
      journalChannel0.close();
      try { 
        journalChannel0.forceWrite(false);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(ClosedChannelException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, (-811L));
      FileSystemHandling.shouldAllThrowIOExceptions();
      JournalChannel journalChannel1 = new JournalChannel((File) null, (-811L));
      try { 
        journalChannel1.close();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel((File) null, 826, 826, (-2145937582), serverConfiguration0, (FileChannelProvider) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockFile mockFile0 = new MockFile("\"no(");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 1, (-1L), 1, serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel((File) null, (-1L), (-1L), (-279), serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -279 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockFile mockFile0 = new MockFile("us@+jxT*", "us@+jxT*");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 4, (-9223372036854775808L), 4, serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockFile mockFile0 = new MockFile("us@+jxT*", "us@+jxT*");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 1367L, 1487L, 2147483136, 846L, serverConfiguration0, defaultFileChannelProvider0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, (-922L), 2353L, 6, 1024L, (ServerConfiguration) null, (FileChannelProvider) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel((File) null, 5242880L, 4, 4, 4, serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      MockFile mockFile0 = new MockFile("minNumRacksPerWriteQuorum", "org.apache.bookkeeper.conf.readsystemproperties");
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 6, 6, (-22), (-1814L), serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -22 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MockFile mockFile0 = new MockFile("us@+j*", "us@+j*");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 4, 4, (-2044), 4, false, 4, serverConfiguration0, (FileChannelProvider) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel((File) null, (-23), (-23), (-23), (-23), true, (-23), serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.ByteBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel((File) null, 578L, 578L, (-2147483646), 4, false, 2144244607, serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -2147483646 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MockFile mockFile0 = new MockFile("E:=-v5D?.\"^Ut7cL(9}", "eIh'v");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 14L, 16, 16, 0, true, 0, serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel((File) null, 4, (-12345L), 4, 2143297520, false, (-2095), serverConfiguration0, defaultFileChannelProvider0);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Invalid journal format to write : version = -2095
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Ignore // il test è sbagliato perchè la versione 2 non è più supportate per la creazione di journalChannel
  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MockFile mockFile0 = new MockFile("ailed to rename file ", "ailed to rename file ");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      Long long0 = Long.valueOf(0L);
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 2, 0L, 2, 2146796673, false, 2, (Journal.BufferedChannelBuilder) null, serverConfiguration0, defaultFileChannelProvider0, long0);
  }

    @Test(timeout = 4000)
    public void test21bis() throws Throwable {
        // SETUP
        MockFile mockFile0 = new MockFile("failed_version_test", "failed_version_test");
        ServerConfiguration serverConfiguration0 = new ServerConfiguration();
        Long long0 = Long.valueOf(0L);
        DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();

        JournalChannel journalChannel0 = null;

        try {
            journalChannel0 = new JournalChannel(
                    mockFile0,
                    2,
                    0L,
                    2,
                    512,
                    false,
                    2,
                    null,
                    serverConfiguration0,
                    defaultFileChannelProvider0,
                    long0
            );

            fail("Expecting exception: IOException");

        } catch(IOException e) {

            verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
        }
    }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MockFile mockFile0 = new MockFile("us-f+jxT*");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      Long long0 = Long.valueOf((long) 300);
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, (-1085L), 300, (-3836), (-3836), false, 300, (Journal.BufferedChannelBuilder) null, serverConfiguration0, defaultFileChannelProvider0, long0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.ByteBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MockFile mockFile0 = new MockFile("E:=-v5D?.\"^Ut7cL(9}");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      Long long0 = Long.valueOf((long) 8);
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 1266, 8, 2, 0, false, (-1230), (Journal.BufferedChannelBuilder) null, serverConfiguration0, defaultFileChannelProvider0, long0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MockFile mockFile0 = new MockFile("File ");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 1, 1592L, 389, serverConfiguration0, defaultFileChannelProvider0);
      journalChannel0.forceWrite(false);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, (-811L));
      JournalChannel journalChannel1 = new JournalChannel((File) null, (-811L));
      // Undeclared exception!
      try { 
        journalChannel1.forceWrite(false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MockFile mockFile0 = new MockFile("U.%Yre$-}");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      Long long0 = new Long(389);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("U.%Yre$-}/1.txn");
      byte[] byteArray0 = new byte[6];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      Journal.BufferedChannelBuilder journal_BufferedChannelBuilder0 = mock(Journal.BufferedChannelBuilder.class, new ViolatedAssumptionAnswer());
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 1, (-1945L), 1954, 1954, true, 105, journal_BufferedChannelBuilder0, serverConfiguration0, defaultFileChannelProvider0, long0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, (-811L));
      JournalChannel journalChannel1 = new JournalChannel((File) null, (-811L));
      journalChannel1.close();
      try { 
        journalChannel1.read(journalChannel0.zeros);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(ClosedChannelException e) {
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MockFile mockFile0 = new MockFile("C");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 1048576L, 300, 300, 300, true, 2147483631, serverConfiguration0, defaultFileChannelProvider0);
      journalChannel0.preAllocIfNeeded(300);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MockFile mockFile0 = new MockFile("", "");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 844, 1020L, 2, serverConfiguration0, defaultFileChannelProvider0);
      journalChannel0.preAllocIfNeeded((-1L));
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MockFile mockFile0 = new MockFile("C");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 1048576L, 300, 300, 300, true, 2147483631, serverConfiguration0, defaultFileChannelProvider0);
      MockFile mockFile1 = new MockFile("%@b;gCa");
      JournalChannel.renameJournalFile(mockFile0, mockFile1);
      assertTrue(mockFile1.canWrite());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      File file0 = MockFile.createTempFile("'&!Yd", "'&!Yd");
      try { 
        JournalChannel.renameJournalFile(file0, (File) null);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Failed to rename file /tmp/'&!Yd0'&!Yd to null
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MockFile mockFile0 = new MockFile("C");
      try { 
        JournalChannel.renameJournalFile(mockFile0, mockFile0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Failed to rename file C to C
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      try { 
        JournalChannel.renameJournalFile((File) null, (File) null);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Failed to rename file null to null
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MockFile mockFile0 = new MockFile("c");
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("c/ffffffffffffff0b.txn");
      byte[] byteArray0 = new byte[8];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, (-245L));
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      File file0 = MockFile.createTempFile("PluWf", "PluWf");
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(file0, 1485L, (-2145657555L), (-1), 2006L, (ServerConfiguration) null, defaultFileChannelProvider0);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // File /tmp/PluWf0PluWf/5cd.txn suddenly appeared, is another bookie process running?
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, (-811L));
      JournalChannel journalChannel1 = new JournalChannel((File) null, (-811L));
      try { 
        journalChannel1.getBufferedChannel();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Read only journal channel
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MockFile mockFile0 = new MockFile("ailed to rename file ", "ailed to rename file ");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      Long long0 = Long.valueOf((long) 2);
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 3, 2, 2, 3, true, 3, (Journal.BufferedChannelBuilder) null, serverConfiguration0, defaultFileChannelProvider0, long0);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Invalid journal format to write : version = 3
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      MockFile mockFile0 = new MockFile("ailed to rename file ", "ailed to rename file ");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      Long long0 = Long.valueOf((long) 300);
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = null;
      try {
        journalChannel0 = new JournalChannel(mockFile0, 300, 300, 1266, 300, false, 1266, (Journal.BufferedChannelBuilder) null, serverConfiguration0, defaultFileChannelProvider0, long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.JournalChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MockFile mockFile0 = new MockFile("File ");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      Long long0 = new Long(2147483647L);
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 1, 1592L, 389, serverConfiguration0, defaultFileChannelProvider0);
      BufferedChannel bufferedChannel0 = journalChannel0.getBufferedChannel();
      Journal.BufferedChannelBuilder journal_BufferedChannelBuilder0 = mock(Journal.BufferedChannelBuilder.class, new ViolatedAssumptionAnswer());
      doReturn(bufferedChannel0).when(journal_BufferedChannelBuilder0).create(any(java.nio.channels.FileChannel.class) , anyInt());
      JournalChannel journalChannel1 = new JournalChannel(mockFile0, (-32768L), 2147483647L, 1, 389, false, 1954, journal_BufferedChannelBuilder0, serverConfiguration0, defaultFileChannelProvider0, long0);
      int int0 = journalChannel1.getFormatVersion();
      assertEquals(1954, int0);
      assertEquals(512L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      MockFile mockFile0 = new MockFile("us-@f+jxT*", "us-@f+jxT*");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 4, 1304L, 3, serverConfiguration0, defaultFileChannelProvider0);
      JournalChannel journalChannel1 = new JournalChannel(mockFile0, 4, 4, (-775), 2528L, serverConfiguration0, defaultFileChannelProvider0);
      assertFalse(journalChannel1.equals((Object)journalChannel0));
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      MockFile mockFile0 = new MockFile("us@+jxT*", "us@+jxT*");
      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
      DefaultFileChannelProvider defaultFileChannelProvider0 = new DefaultFileChannelProvider();
      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 4, 4, 4, 4, true, 4, serverConfiguration0, defaultFileChannelProvider0);
      journalChannel0.forceWrite(true);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      JournalChannel journalChannel0 = new JournalChannel((File) null, (-811L));
      int int0 = journalChannel0.read(journalChannel0.zeros);
      assertEquals(0, int0);
  }
}
